### ISSUE TITLE
missing RS232 library for NativeSerial

### ISSUE THREAD

**Issue by civet** [benkuper/AIR-NativeExtensions#12]
I am trying to recomplie NativeSerial.ane for MacOS 64bit.
I found that missing a header file call "rs232.h", could you please offer these files again?

**Comment by benkuper** [comment]
Hello, this repo is officially not maintained anymore as Adobe has fucked it up quite good for devs.
Nonetheless, quick search on google... https://lmgtfy.com/?q=rs232.h
Have a nice day !
