### ISSUE TITLE
Spout2AIR Demo and recomplie Error

### ISSUE THREAD

**Issue by dannyboom** [benkuper/AIR-NativeExtensions#2]
Hi Ben,
Thanks for your code.

I try to make a AIR demo, but appear the following error:

[SWF] benkuper.nativeExtensions.Spout – 6656 bytes after decompression
[SWF] benkuper.nativeExtensions.BaseExtension – 2630 bytes after decompression
[SWF] ribbons.swf – 29357 bytes after decompression
ArgumentError: Error #3500: The extension context does not have a method with the name init.
at flash.external::ExtensionContext/_call()
at flash.external::ExtensionContext/call()
at benkuper.nativeExtensions::Spout()[D:\Documents\Perso\Projects\AIR\NativeExtensions\Spout2AIR\ane_src\as3_src\benkuper\nativeExtensions\Spout.as:33]
at Spout2Demo()[D:001_desarrollo\WorkSpace4.7\ribbons\src\Spout2Demo.as:38]
at runtime::ContentPlayer/loadInitialContent()
at runtime::ContentPlayer/playRawContent()
at runtime::ContentPlayer/playContent()
at runtime::AppRunner/run()
at ADLAppEntry/run()
at global/runtime::ADLEntry()
[UnloadSWF] ribbons.swf
Test Movie terminated.

I try to recomplie ane but the repositories dont appear Backup folder in native-scr and try to make again the DLL but appear compilations errors. Because we try to integrate Spout2 and not compatible.

 Can you help me ?

Thanks and good day!!!

**Comment by varadig** [comment]
Hi,

I have the same issue, what's wrong with the code?

thanks

**Comment by benkuper** [comment]
Hi,
it may be a dependency issue, usually this kind of error is due to a bad initialization of the dll and AIR is unable to list the available functions.
Can you tell me what's your environment (OS, software versions, etc.)

**Comment by varadig** [comment]
I used IntelliJ IDE 14, with AIR17 under Windows and also tried under OSX.

thanks

**Comment by benkuper** [comment]
Hi, i updated the repo, please check this (i tested on Windows, it works).
You may need to add pthreadVC2 to your flex_sdk/bin for testing, i included it in the /bin of the demo folder so you just have to copy it next to the adl.exe from your sdk.
Spout is only working on Windows as it relies on DirectX. If you want to use these features on OSX, you should use Syphon.

**Comment by varadig** [comment]
Hi, sadly it's not work, the result is the same:
"C:\Program Files\JetBrains\IntelliJ IDEA 14.1\jre\jre\bin\java.exe" "-Dapplication.home=C:\Documents and Settings\varadig\My Documents\SDK\AIR_17" -Xmx384m -Dsun.io.useCanonCaches=false -Dfile.encoding=UTF-8 -Djava.awt.headless=true -Duser.language=en -Duser.region=en -Xmx512m -classpath "C:/Documents and Settings/varadig/My Documents/SDK/AIR_17/lib/legacy/fdb.jar" flex.tools.debugger.cli.DebugCLI
Adobe fdb (Flash Player Debugger) [build development]
Copyright (c) 2004-2007 Adobe, Inc. All rights reserved.
Waiting for Player to connect
"C:\Documents and Settings\varadig\My Documents\SDK\AIR_17\bin\adl.exe" -profile extendedDesktop -extdir C:\DOCUME~1\varadig\LOCALS~1\Temp\IntelliJ_ANE_unzipped "C:\Documents and Settings\varadig\My Documents\Work\AS3\SPOUT\bin\application.xml" "C:\Documents and Settings\varadig\My Documents\Work\AS3\SPOUT\bin"
Player connected; session starting.
[Fault] exception, information=ArgumentError: Error #3500: The extension context does not have a method with the name init.

I copied the dll to my sdk folder, and tried to build the Spot2Demo.as.

**Comment by benkuper** [comment]
Could you test with flashDevelop ? i only use intellij on OSX, and for me it's working with FlashDevelop on windows

**Comment by benkuper** [comment]
I commited a new version, compiled the dll in release instead of debug.
You may want to test this last version of the ane, and also install VS2012 redistributables if you don't have Visual Studio installed.
http://www.microsoft.com/fr-fr/download/details.aspx?id=30679

**Comment by owenhindley** [comment]
Installing VS2012 redistributables did the trick for me, thanks!
