### ISSUE TITLE
NativeSerial.ane init error

### ISSUE THREAD

**Issue by feipinxiang** [benkuper/AIR-NativeExtensions#5]
Thanks for your code.sorry for my poor english.
i try to make a air demo by the NativeSerial.ane. the flash cc(air 16/17/18)show me a error like this.

extContext test : [object ExtensionContext]
ArgumentError: Error #3500: The extension context does not have a method with the name init.
	at flash.external::ExtensionContext/_call()
	at flash.external::ExtensionContext/call()
	at benkuper.nativeExtensions::NativeSerial()[D:\Documents\Perso\Projects\AIR\NativeExtensions\NativeSerial\ane_src\as3_src\benkuper\nativeExtensions\NativeSerial.as:37]
	at benkuper.nativeExtensions::NativeSerial$/init()[D:\Documents\Perso\Projects\AIR\NativeExtensions\NativeSerial\ane_src\as3_src\benkuper\nativeExtensions\NativeSerial.as:62]

my code very simple.
private var sp1:SerialPort;		
public function test() 
{
	NativeSerial.init();//it's show error at here.
	sp1 = NativeSerial.getPort("COM3");
	trace(sp1);
}

**Comment by benkuper** [comment]
Hello,
this error means that the extension did not load properly, it is often a dependency problem or a blocking error at the invokation of the dll (i assume you're on Windows since you're searching for port call "COM3")
as i removed all external dependencies in my last version of NativeSerial, i would guess it comes from the CLR / .NET incompatibilty.
Which version of .NET do you have installed ? i guess it should be at least 3.5, preferrably 4.5 or later.
Also, can you try the as3_demo project with FlashDevelop ?

**Comment by feipinxiang** [comment]
yes,i work on windows 8.1_64. this system has .NET3.5 and 4.5.
i tried the as3_demo,it's have the same error.

**Comment by bdaver** [comment]
This is still a problem in Windows. Tried installing pthread dll file and latest .net frameworks.

**Comment by feipinxiang** [comment]
i already has pthreadGC2.dll in c://windows/system32 and syswow64 folder.
and install this driver http://www.ftdichip.com/Drivers/VCP.htm

i need to install some other external dependencies?
can you introduce the Microsoft DLL dependency?

**Comment by benkuper** [comment]
From which IDE are you trying to compile ? FlashDevelop, IntelliJ or Flash Pro CC ?
When debugging from FlashDevelop, you need to put the dependency dlls in the same folder as the adl.exe file that is debugging (for me it looks like that : AppData\Local\FlashDevelop\Apps\ascsdk\20.0.0\bin)

The dependencies i can think of are msvcr100.dll / msvcp100.dll or msvcr110.dll / msvcp110.dll and pthreadGC2.dll / pthreadVC2.dll

When exporting, the dll needs to be aside the main .exe file

When using Flash Pro, you should also try copying those files inside the folder that contains adl.exe (i would guess Program Files/Adobe/Flash Pro/ ... /... / bin )

**Comment by feipinxiang** [comment]
thx. I use flashPro.
I can debugging and running in my computer now, but copy the release program to another computer unusable(win10_64 with all dll what you listed). i will try other computer and system in tomorrow.

**Comment by benkuper** [comment]
Hello, i added instructions on how to handle the dll and dependency problem in the main Readme.
