### ISSUE TITLE
NativeDMXController sendValue 

### ISSUE THREAD

**Issue by denischiron** [benkuper/AIR-NativeExtensions#7]
Hello,

Thanks for your help with the DLL.

Now I'm testing your ANE with a real device.
And your library correctly recognizes the "DMX USB PRO MK2" device !

But when I send value, it doesn't seem to work.
I've tried with the ENTEC PRO-Manager software and it works.

In your as3 sources on github, there is no implementation for the two functions : 
- sendValue (channel:int, value:int) : void { }
- sendValues (values:Vector.<int>, offset:int = 0) : void { }

I can't find any reference to the native functions declared in "DMXExtension.cpp" : openDevice, sendValue & sendValues.

I was searching for something like : extContext.call("sendValue "), as you've done in NativeDXMController.

Maybe these functions are in the compiled ANE/SWC but It doesn't seem to send any dmx data.

Am I missing something ?

Thanks by advance,

Cheers,
Denis

**Comment by denischiron** [comment]
Hi,

I've completed your AS3 code to allow native calls to the function "sendValue".
I've rebuilt the .swc and the .ane (but not your DLL).

Here is the as3 call to sendValue:
var sendResult:Boolean = extContext.call("sendValue", channel, value) as Boolean;

When I send the value, there is a reaction from the light but it doesn't seem to be related to channel nor value. And the light has only a small variation in intensity, up and down, three ou four times in a row !

(The DMX harware includes : the ENTTEC Device + a dimmer + a light.)

I'm not a C-developer at all. So when I look at the C code for the sendValues, I can't figure out where the arguments are considered. In FREObject sendValue(FREContext ctx, void* funcData, uint32_t argc, FREObject argv[]), there is no reference to argv.

And I doesn't understand why there is this loop from 1 to 1000 in which there is the call to the function : FTDI_SendData(SET_DMX_TX_MODE, myDmx, DMX_DATA_LENGTH)

Could you give me some hints ?

Have you already controlled some DMX lights with these extension and DLL ?
In that case, could you tell me what was your DMX/light configuration. Maybe the dimmer is the problem (although the enttec software can control the light perfectly in the same configuration).

Thanks by advance,
Cheers,
Denis

**Comment by denischiron** [comment]
Ok, I've found a reference to the DLL code in the "enttec_pro usb_pro_example.cpp"
Cf http://www.enttec.com/download/pro_example_v2.zip

I will try to compile the DLL with something like this.

FREObject sendValue(FREContext ctx, void* funcData, uint32_t argc, FREObject argv[])
{
unsigned char myDmx[DMX_DATA_LENGTH];
int channel =  argv[0];
int value=  argv[1];
myDmx[0] = 0;
myDmx[channel]=value;
int res = FTDI_SendData(SET_DMX_TX_MODE,myDmx,DMX_DATA_LENGTH);
...
}

I'll let you know if I succeed (if you're interested, of course).

Cheers,
Denis

**Comment by benkuper** [comment]
Hello,
you're right, the code that is in this repo is not functional at all
i actually don't understand, i didn't look at this code for a moment but it seems like i don't have the real extension code anymore.
I wrote the DMX extension (the real one) few years ago, but in the meantime i got my computer stolen with a lot of unarchived projects, most of the AIR Extensions that are on the repo have been made again by memory, and i may not have finished to rewrite the DMX extension as i didn't really needed to recompile it anymore. i don't really know why i uploaded the code in this state, but if you have got time to rewrite a new one, feel free and i'll integrate the functions in the extension

**Comment by benkuper** [comment]
you may try this ane otherwise, it worked for me last time i checked :

http://benjamin.kuperberg.fr/download/NativeDMXController.ane

if it works, i'll add a link to the Readme so people who only want's the ANE can grab  a working one

**Comment by denischiron** [comment]
Hello,

I've tested the extension but It doesn't work for me.
I've tried to send value to the DMX but no reaction from the light...

But this morning, I've changed the C version of sendValue, recompiled the DLL with Visual Studio, rebuilt the ANE, and it worked.

I will try to complete the sendValues tomorrow (I've found an tutorial here http://www.adobe.com/devnet/air/articles/transferring-data-ane-ios-pt2.html to send Arrays and Vectors to C) though I think I don't need it for my project.

I'll clean up the code a bit, and will send it to you.

Thanks for your help and inspiration : I learned a lot from your project and code !

Denis

**Comment by denischiron** [comment]
Hello,

I've finished the sendValues (Vector of ints) version.

Both function - sendValue & sendValues  - have been tested with the ENTTEC hardware.

Here are :
-the sources of as3 and c++ :
http://redburn.free.fr/dmx/ane_src.zip
- the compiled .ane
http://redburn.free.fr/dmx/NativeDMXController.ane
- and a simple example
http://redburn.free.fr/dmx/DemoDMX.zip

Tell me when you will get these files, since I'll probably remove them in a near future.

If you find them useful, feel free to include them in your repository.

Cheers,
Denis

**Comment by denischiron** [comment]
Maybe you shoud complete the READ ME for the 2 Microsoft DLL dependency.
The issue  https://github.com/benkuper/AIR-NativeExtensions/issues/5 is probably related to this.

**Comment by benkuper** [comment]
I added the dependencies and instructions in the main Readme.
Thank for everything !

**Comment by slaymantis** [comment]
I know this is a very old post - but any chance the NativeDMXContoller got fixed?

**Comment by benkuper** [comment]
Hey, sorry man Adobe AIR is finished, at least for me...

**Comment by slaymantis** [comment]
Thanks I was just busy with a legacy project. What tech have you started focusing more on these days?

**Comment by benkuper** [comment]
I completely switched all my UI based dev on JUCE, you can check Chataigne (http://github.com/benkuper/Chataigne)  as a reference of my work with it.
