### ISSUE TITLE
Spout2Air "shareTexture"

### ISSUE THREAD

**Issue by ritamaia** [benkuper/AIR-NativeExtensions#8]
Hey!
Im using Spout2Air to send my app to Resolume but i dont have “shareTexture” function inside the ANE class. I’ve downloaded the demo and the problem continues.
Im i missing something?

**Comment by benkuper** [comment]
Hello,
i'm sorry i forgot to commit my latest changes.
The demo should work ok now (i changed the method names)

**Comment by dedosmedia** [comment]
Hi @benkuper 
I know this is too old, and maybe you are not using AIR anymore. 
I would like to know if the Spout2AIR ANE, will also work as a Spout Receiver?
Thanks so much!
